import type { Question, Option } from '../data/types';

const scale = (labels: string[]): Option[] => labels.map((label, i) => ({ key: String(i + 1), label, value: i + 1, scoring: true }));
const multi = (labels: [string, string][]): Option[] => labels.map(([key, label]) => ({ key, label }));

export const facultyQuestions: Question[] = [
  {
    id: 'F10',
    number: 10,
    section: 'Section C — Teaching Practice & Learning Technology',
    text: 'How frequently do you use the following resources or technologies in your teaching?',
    type: 'matrix',
    rows: multi([
      ['powerpoint', 'PowerPoint/presentation slides'],
      ['whiteboard', 'Whiteboard'],
      ['lms', 'University LMS/portal'],
      ['videos', 'Videos'],
      ['virtual-labs', 'Virtual laboratories'],
      ['ai-tools', 'AI tools'],
    ]),
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost every session']),
    indicatorId: 'IND-TECH-FAC',
    constructId: 'learning-technology-integration',
    whyThisRespondent: 'Lecturers know what they actually use. AQIP compares this with what the institution declares available, what students report experiencing, and system activity.',
  },
  {
    id: 'F11',
    number: 11,
    section: 'Section C — Teaching Practice & Learning Technology',
    text: 'How often do your teaching activities provide students with opportunities to actively participate rather than only receive information?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-ACT-01',
    constructId: 'active-learning-engagement',
    whyThisRespondent: 'This asks what teaching provides, not how effective it is. It is compared with what students report experiencing.',
  },
  {
    id: 'F13',
    number: 13,
    section: 'Section C — Teaching Practice & Learning Technology',
    text: 'How clear are your explanations and instructions when teaching?',
    type: 'single',
    options: scale(['Very unclear', 'Somewhat unclear', 'Neither', 'Clear', 'Very clear']),
    indicatorId: 'IND-CLR-02',
    constructId: 'instructional-clarity',
    whyThisRespondent: 'A self-rating, treated as one reading among three: student perception and observation records provide the others.',
  },
  {
    id: 'F19',
    number: 19,
    section: 'Section E — Assessment & Feedback',
    text: 'How often do you use the intended learning outcomes to determine what is assessed?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-ALN-01',
    constructId: 'assessment-alignment',
    whyThisRespondent: 'Lecturers design the assessment. Their report of practice is compared with the cognitive level the assessment papers actually carry.',
  },
  {
    id: 'F21',
    number: 21,
    section: 'Section E — Assessment & Feedback',
    text: 'How often do your assessments require students to apply knowledge or skills to realistic, practical, professional or unfamiliar situations?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-CGD-02',
    constructId: 'cognitive-demand',
    whyThisRespondent: 'Faculty report of assessment demand, compared with student experience and artefact analysis of the papers.',
  },
  {
    id: 'F23',
    number: 23,
    section: 'Section E — Assessment & Feedback',
    text: 'How often is feedback designed to help students improve subsequent work or learning?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-FBQ-02',
    constructId: 'feedback-quality',
    whyThisRespondent: 'Design intent of feedback is known to the person who writes it. Whether it could be used is known to the student and to the assessment schedule.',
  },
  {
    id: 'F25',
    number: 25,
    section: 'Section E — Assessment & Feedback',
    text: 'What factors make it difficult to provide feedback promptly and/or effectively?',
    note: 'Select all that apply.',
    type: 'multi',
    options: multi([
      ['class-size', 'Large class sizes'],
      ['assessment-count', 'Number of assessments'],
      ['marking-time', 'Marking time'],
      ['admin-workload', 'Administrative workload'],
      ['multiple-courses', 'Multiple courses'],
      ['other-teaching', 'Other teaching responsibilities'],
      ['marking-tools', 'Assessment/marking tools'],
      ['unclear-criteria', 'Unclear assessment criteria'],
      ['institutional-processes', 'Institutional processes'],
      ['none', 'No significant difficulty'],
      ['other', 'Other'],
    ]),
    indicatorId: 'IND-FBB-01',
    constructId: 'feedback-timeliness',
    whyThisRespondent: 'Constraints on feedback are known to those doing the marking. Actual turnaround is taken from records, not from lecturer estimates.',
  },
  {
    id: 'F37',
    number: 37,
    section: 'Section I — Overall Faculty Assessment',
    text: 'Overall, how effective do you consider your current teaching approach in supporting students to achieve the intended learning outcomes?',
    type: 'single',
    options: scale(['Very ineffective', 'Ineffective', 'Neither', 'Effective', 'Very effective']),
    indicatorId: 'IND-EFF-01',
    whyThisRespondent: 'A variable of interest, not a construct measure. It is compared with student experience and learning outcomes; it does not stand in for them.',
  },
  {
    id: 'F38',
    number: 38,
    section: 'Section I — Overall Faculty Assessment',
    text: 'What is the single biggest factor currently limiting the quality or effectiveness of your teaching?',
    note: 'Open text.',
    type: 'open',
    whyThisRespondent: 'Open responses are stored as qualitative evidence. They illustrate findings; they are not scored.',
  },
];
