import type { Question, Option } from '../data/types';

const scale = (labels: string[]): Option[] => labels.map((label, i) => ({ key: String(i + 1), label, value: i + 1, scoring: true }));
const multi = (labels: [string, string][]): Option[] => labels.map(([key, label]) => ({ key, label }));

/** Validator options: each answer carries the value it implies on the paired item's 1-5 scale. */
const anchored = (rows: [string, string, number | null][]): Option[] =>
  rows.map(([key, label, implies]) =>
    implies === null ? { key, label, scoring: false } : { key, label, implies, scoring: true },
  );

export const facultyQuestions: Question[] = [
  {
    id: 'F10',
    number: 10,
    section: 'Section C — Teaching Practice & Learning Technology',
    text: 'How frequently do you use the following resources or technologies in your teaching?',
    type: 'matrix',
    rows: multi([
      ['powerpoint', 'PowerPoint/presentation slides'],
      ['whiteboard', 'Whiteboard'],
      ['lms', 'University LMS/portal'],
      ['videos', 'Videos'],
      ['virtual-labs', 'Virtual laboratories'],
      ['ai-tools', 'AI tools'],
    ]),
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost every session']),
    indicatorId: 'IND-TECH-FAC',
    constructId: 'learning-technology-integration',
    whyThisRespondent: 'Lecturers know what they actually use. AQIP compares this with what the institution declares available, what students report experiencing, and system activity.',
  },
  {
    id: 'F11',
    number: 11,
    section: 'Section C — Teaching Practice & Learning Technology',
    text: 'How often do your teaching activities provide students with opportunities to actively participate rather than only receive information?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-ACT-01',
    constructId: 'active-learning-engagement',
    whyThisRespondent: 'This asks what teaching provides, not how effective it is. It is compared with what students report experiencing.',
  },
  {
    id: 'F-V11',
    number: 12,
    section: 'Section C — Teaching Practice & Learning Technology',
    text: 'In a typical two-hour session on this course, roughly how many minutes are students doing something other than listening or copying?',
    note: 'Asked to check the previous answer against a quantity rather than a frequency.',
    type: 'single',
    options: anchored([
      ['none', 'None — the session is delivery throughout', 1],
      ['lt10', 'Under 10 minutes', 2],
      ['10to25', '10 to 25 minutes', 3],
      ['25to45', '25 to 45 minutes', 4],
      ['gt45', 'More than 45 minutes', 5],
      ['x1', 'It varies too much to estimate', null],
    ]),
    validates: 'F11',
    validationKind: 'behavioural-anchor',
    constructId: 'active-learning-engagement',
    whyThisRespondent: 'Only the person teaching knows how the time is spent. A quantity of minutes is a harder reading than a frequency word, and it can be set against enrolment relative to room capacity.',
  },
  {
    id: 'F13',
    number: 13,
    section: 'Section C — Teaching Practice & Learning Technology',
    text: 'How clear are your explanations and instructions when teaching?',
    type: 'single',
    options: scale(['Very unclear', 'Somewhat unclear', 'Neither', 'Clear', 'Very clear']),
    indicatorId: 'IND-CLR-02',
    constructId: 'instructional-clarity',
    whyThisRespondent: 'A self-rating, treated as one reading among three: student perception and observation records provide the others.',
  },
  {
    id: 'F19',
    number: 19,
    section: 'Section E — Assessment & Feedback',
    text: 'How often do you use the intended learning outcomes to determine what is assessed?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-ALN-01',
    constructId: 'assessment-alignment',
    whyThisRespondent: 'Lecturers design the assessment. Their report of practice is compared with the cognitive level the assessment papers actually carry.',
  },
  {
    id: 'F21',
    number: 21,
    section: 'Section E — Assessment & Feedback',
    text: 'How often do your assessments require students to apply knowledge or skills to realistic, practical, professional or unfamiliar situations?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-CGD-02',
    constructId: 'cognitive-demand',
    whyThisRespondent: 'Faculty report of assessment demand, compared with student experience and artefact analysis of the papers.',
  },
  {
    id: 'F-V21',
    number: 22,
    section: 'Section E — Assessment & Feedback',
    text: 'In your most recent assessment on this course, roughly what share of the marks could only be earned by applying knowledge to a situation not already worked through in class?',
    note: 'Asked to check the previous answer against a specific paper.',
    type: 'single',
    options: anchored([
      ['lt10', 'Under 10% of the marks', 1],
      ['10to25', '10–25% of the marks', 2],
      ['25to50', '25–50% of the marks', 3],
      ['50to75', '50–75% of the marks', 4],
      ['gt75', 'Over 75% of the marks', 5],
      ['x1', 'I would have to look at the paper', null],
    ]),
    validates: 'F21',
    validationKind: 'recall-anchor',
    constructId: 'cognitive-demand',
    whyThisRespondent: 'This is the one validator with an independent objective counterpart: the same share is computed directly from the marks in the assessment artefacts, so lecturer report, student report and the paper itself can all be read against one another.',
  },
  {
    id: 'F23',
    number: 23,
    section: 'Section E — Assessment & Feedback',
    text: 'How often is feedback designed to help students improve subsequent work or learning?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Almost always']),
    indicatorId: 'IND-FBQ-02',
    constructId: 'feedback-quality',
    whyThisRespondent: 'Design intent of feedback is known to the person who writes it. Whether it could be used is known to the student and to the assessment schedule.',
  },
  {
    id: 'F-V23',
    number: 24,
    section: 'Section E — Assessment & Feedback',
    text: 'After your most recent feedback release on this course, how long was it until the next task students could apply that feedback to?',
    note: 'Asked to check the previous answer against the assessment calendar.',
    type: 'single',
    options: anchored([
      ['none', 'There was no further task that semester', 1],
      ['gt28', 'More than four weeks', 2],
      ['15to28', 'Two to four weeks', 3],
      ['8to14', 'One to two weeks', 4],
      ['lt7', 'Within a week', 5],
      ['x1', 'I do not know', null],
    ]),
    validates: 'F23',
    validationKind: 'consequence-anchor',
    constructId: 'feedback-quality',
    whyThisRespondent: 'Feedback designed to improve subsequent work presupposes subsequent work. This asks whether any existed, and is checked directly against the assessment schedule and the feedback-release timestamps.',
  },
  {
    id: 'F25',
    number: 25,
    section: 'Section E — Assessment & Feedback',
    text: 'What factors make it difficult to provide feedback promptly and/or effectively?',
    note: 'Select all that apply.',
    type: 'multi',
    options: multi([
      ['class-size', 'Large class sizes'],
      ['assessment-count', 'Number of assessments'],
      ['marking-time', 'Marking time'],
      ['admin-workload', 'Administrative workload'],
      ['multiple-courses', 'Multiple courses'],
      ['other-teaching', 'Other teaching responsibilities'],
      ['marking-tools', 'Assessment/marking tools'],
      ['unclear-criteria', 'Unclear assessment criteria'],
      ['institutional-processes', 'Institutional processes'],
      ['none', 'No significant difficulty'],
      ['other', 'Other'],
    ]),
    indicatorId: 'IND-FBB-01',
    constructId: 'feedback-timeliness',
    whyThisRespondent: 'Constraints on feedback are known to those doing the marking. Actual turnaround is taken from records, not from lecturer estimates.',
  },
  {
    id: 'F37',
    number: 37,
    section: 'Section I — Overall Faculty Assessment',
    text: 'Overall, how effective do you consider your current teaching approach in supporting students to achieve the intended learning outcomes?',
    type: 'single',
    options: scale(['Very ineffective', 'Ineffective', 'Neither', 'Effective', 'Very effective']),
    indicatorId: 'IND-EFF-01',
    whyThisRespondent: 'A variable of interest, not a construct measure. It is compared with student experience and learning outcomes; it does not stand in for them.',
  },
  {
    id: 'F38',
    number: 38,
    section: 'Section I — Overall Faculty Assessment',
    text: 'What is the single biggest factor currently limiting the quality or effectiveness of your teaching?',
    note: 'Open text.',
    type: 'open',
    whyThisRespondent: 'Open responses are stored as qualitative evidence. They illustrate findings; they are not scored.',
  },
];
