import type { Question, Option } from '../data/types';

const single = (labels: [string, string][]): Option[] => labels.map(([key, label]) => ({ key, label }));
const multi = single;

export const institutionQuestions: Question[] = [
  {
    id: 'I5',
    number: 5,
    section: 'Section B — Academic Intent & Curriculum',
    text: 'Does the programme/course have formally approved intended learning outcomes?',
    type: 'single',
    options: single([['yes', 'Yes'], ['no', 'No'], ['not-sure', 'Not sure']]),
    indicatorId: 'IND-ILO-01',
    constructId: 'intended-learning-outcomes',
    whyThisRespondent: 'Formal approval status is institutional knowledge. The curriculum document provides the second reading.',
  },
  {
    id: 'I6',
    number: 6,
    section: 'Section B — Academic Intent & Curriculum',
    text: 'Which of the following does the curriculum formally align with?',
    note: 'Select all that apply.',
    type: 'multi',
    options: multi([
      ['institutional', 'Institutional academic requirements'],
      ['nuc', 'NUC BMAS/CCMAS or applicable regulatory requirements'],
      ['professional', 'Professional-body requirements'],
      ['industry', 'Industry/employer expectations'],
      ['international', 'International benchmarks'],
      ['other-external', 'Other external standards'],
      ['none', 'None'],
      ['not-sure', 'Not sure'],
    ]),
    indicatorId: 'IND-CAL-01',
    constructId: 'curriculum-alignment',
    whyThisRespondent: 'Alignment claims are held by curriculum governance. Direct variables retained from the original AQIP: NUC, professional body, industry, international.',
  },
  {
    id: 'I9',
    number: 9,
    section: 'Section C — Learning Provision, Resources & Continuity',
    text: 'Which learning resources and facilities are formally available to students?',
    note: 'Select all that apply.',
    type: 'multi',
    options: multi([
      ['lecture-rooms', 'Lecture rooms'],
      ['laboratories', 'Laboratories'],
      ['library', 'Library'],
      ['computer-facilities', 'Computer facilities'],
      ['specialist-equipment', 'Specialist equipment'],
      ['simulation', 'Simulation facilities'],
      ['virtual-labs', 'Virtual laboratories'],
      ['wifi', 'Internet/Wi-Fi'],
      ['lms', 'Learning Management System'],
      ['digital-library', 'Digital library/resources'],
      ['other', 'Other'],
    ]),
    indicatorId: 'IND-PROV-01',
    constructId: 'learning-resources-facilities',
    whyThisRespondent: 'Declared provision. AQIP holds this apart from accessibility (students) and use (lecturers, system data).',
  },
  {
    id: 'I11',
    number: 11,
    section: 'Section C — Learning Provision, Resources & Continuity',
    text: "What are the main limitations affecting students' access to required learning resources?",
    note: 'Select all that apply.',
    type: 'multi',
    options: multi([
      ['capacity', 'Insufficient quantity/capacity'],
      ['equipment', 'Equipment availability'],
      ['connectivity', 'Internet/connectivity'],
      ['power', 'Electricity/power'],
      ['cost', 'Cost to students'],
      ['hours', 'Restricted access hours'],
      ['devices', 'Digital access/device limitations'],
      ['software', 'Software/licensing'],
      ['space', 'Physical learning space'],
      ['staffing', 'Staffing/technical support'],
      ['none', 'No significant limitations'],
      ['other', 'Other'],
    ]),
    indicatorId: 'IND-PROV-02',
    constructId: 'resource-accessibility-availability',
    whyThisRespondent: "The institution's own account of access barriers, set beside students' reported ease of access.",
  },
  {
    id: 'I24',
    number: 24,
    section: 'Section E — Assessment & Feedback',
    text: 'Which assessment quality-assurance mechanisms are used?',
    note: 'Select all that apply.',
    type: 'multi',
    options: multi([
      ['internal-moderation', 'Internal moderation'],
      ['external-moderation', 'External moderation'],
      ['double-marking', 'Double marking'],
      ['sampling', 'Sampling of marked work'],
      ['assessment-review', 'Examination/assessment review'],
      ['marking-schemes', 'Marking schemes'],
      ['rubric-review', 'Rubric review'],
      ['programme-review', 'Programme-level review'],
      ['other', 'Other'],
      ['none', 'None'],
    ]),
    indicatorId: 'IND-QA-01',
    constructId: 'moderation-quality-assurance',
    whyThisRespondent: 'Moderation arrangements are institutional process knowledge that students and most lecturers cannot report authoritatively.',
  },
  {
    id: 'I25',
    number: 25,
    section: 'Section E — Assessment & Feedback',
    text: 'Are rubrics or explicit marking criteria provided for applicable assessments?',
    type: 'single',
    options: single([
      ['routinely', 'Routinely'],
      ['some', 'For some assessments'],
      ['rarely', 'Rarely'],
      ['never', 'Never'],
      ['na', 'Not applicable'],
    ]),
    indicatorId: 'IND-TRN-01',
    constructId: 'assessment-transparency',
    whyThisRespondent: 'Institutional policy on rubrics. The uploaded assessment artefacts show whether a rubric was actually present.',
  },
  {
    id: 'I26',
    number: 26,
    section: 'Section E — Assessment & Feedback',
    text: 'Is assessment/feedback turnaround formally monitored?',
    type: 'single',
    options: single([
      ['institutionally', 'Yes, institutionally'],
      ['course-level', 'Yes, at course/department level'],
      ['lecturer-reporting', 'Through lecturer reporting'],
      ['student-feedback', 'Through student feedback'],
      ['none', 'No formal monitoring'],
      ['other', 'Other'],
    ]),
    indicatorId: 'IND-MON-01',
    constructId: 'feedback-timeliness',
    whyThisRespondent: 'How turnaround is monitored is a process fact. Actual turnaround is derived from submission and release timestamps.',
  },
  {
    id: 'I34',
    number: 34,
    section: 'Section G — Academic Governance, Quality Assurance & Improvement',
    text: 'How frequently are academic quality or performance indicators formally reviewed?',
    type: 'single',
    options: single([
      ['continuously', 'Continuously'],
      ['monthly', 'Monthly'],
      ['semester', 'Each semester'],
      ['annually', 'Annually'],
      ['less', 'Less frequently than annually'],
      ['none', 'No formal review'],
    ]),
    indicatorId: 'IND-REV-01',
    constructId: 'monitoring-review',
    whyThisRespondent: 'Review cadence is governance knowledge held by quality assurance and academic administration.',
  },
  {
    id: 'I41',
    number: 41,
    section: 'Section H — Current Quality Issue & Evidence',
    text: 'What is the most significant academic quality issue currently affecting this academic area?',
    note: 'Open response.',
    type: 'open',
    constructId: 'quality-issue-identification',
    whyThisRespondent: 'Qualitative evidence for Quality Issue Identification. It is compared with what the analysis surfaces; it is not scored.',
  },
];
