import type { Question, Option } from '../data/types';

const scale = (labels: string[], escapes: string[] = []): Option[] => [
  ...labels.map((label, i) => ({ key: String(i + 1), label, value: i + 1, scoring: true })),
  ...escapes.map((label, i) => ({ key: `x${i + 1}`, label, scoring: false })),
];

const multi = (labels: [string, string][]): Option[] => labels.map(([key, label]) => ({ key, label }));

export const studentQuestions: Question[] = [
  {
    id: 'S-Q4',
    number: 4,
    section: 'Section B — Learning Resources & Environment',
    text: 'Which of the following have been used as part of teaching or learning in this course?',
    note: 'Select all that apply.',
    type: 'multi',
    options: multi([
      ['powerpoint', 'PowerPoint/presentation slides'],
      ['whiteboard', 'Whiteboard'],
      ['recordings', 'Lecture recordings/videos'],
      ['lms', 'Learning Management System (LMS)'],
      ['online-readings', 'Online readings/materials'],
      ['simulation', 'Simulation tools'],
      ['virtual-labs', 'Virtual laboratories'],
      ['physical-labs', 'Physical laboratories/workshops'],
      ['ai-tools', 'AI tools'],
      ['forums', 'Online discussion forums'],
      ['other', 'Other'],
      ['none', 'None of these'],
    ]),
    indicatorId: 'IND-TECH-STU',
    constructId: 'learning-technology-integration',
    whyThisRespondent: 'Students are the only source for which technologies actually reached the learning experience, as distinct from what was declared available or what lecturers report using.',
  },
  {
    id: 'S-Q5',
    number: 5,
    section: 'Section B — Learning Resources & Environment',
    text: 'How easy is it to access the learning resources you need for this course?',
    type: 'single',
    options: scale(['Very difficult', 'Difficult', 'Neither easy nor difficult', 'Easy', 'Very easy']),
    indicatorId: 'IND-RES-01',
    constructId: 'resource-accessibility-availability',
    whyThisRespondent: 'Accessibility is experienced by the student. A resource can exist and be declared without being reachable.',
  },
  {
    id: 'S-Q8',
    number: 8,
    section: 'Section C — Teaching & Instruction',
    text: "How clear are your lecturer's explanations of course content?",
    type: 'single',
    options: scale(['Very unclear', 'Unclear', 'Neither clear nor unclear', 'Clear', 'Very clear']),
    indicatorId: 'IND-CLR-01',
    constructId: 'instructional-clarity',
    whyThisRespondent: 'Perceived clarity is a student-side reading that AQIP compares with lecturer self-report and observation records.',
  },
  {
    id: 'S-Q11',
    number: 11,
    section: 'Section C — Teaching & Instruction',
    text: 'How often are you given opportunities to actively participate in your learning during classes or other learning activities?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Very often']),
    indicatorId: 'IND-ACT-02',
    constructId: 'active-learning-engagement',
    whyThisRespondent: 'Students report the opportunity as it reached them. Lecturers report the opportunity as provided. The two are compared, not reconciled.',
  },
  {
    id: 'S-Q31',
    number: 31,
    section: 'Section E — Assessment & Feedback',
    text: 'How often do assessments require you to apply, analyse or use your knowledge rather than mainly recall information?',
    type: 'single',
    options: scale(['Never', 'Rarely', 'Sometimes', 'Often', 'Very often'], ['Not sure']),
    indicatorId: 'IND-CGD-01',
    constructId: 'cognitive-demand',
    whyThisRespondent: 'Students experience the cognitive demand of assessment directly. Their reading is set beside lecturer report and the assessment papers themselves.',
  },
  {
    id: 'S-Q33',
    number: 33,
    section: 'Section E — Assessment & Feedback',
    text: 'How useful is the feedback you receive on your work for improving your future performance?',
    type: 'single',
    options: scale(['Not at all useful', 'Slightly useful', 'Moderately useful', 'Very useful', 'Extremely useful'], ['I have not received feedback']),
    indicatorId: 'IND-FBQ-01',
    constructId: 'feedback-quality',
    whyThisRespondent: 'Whether feedback could be used to improve subsequent work is known only to the student who received it.',
  },
  {
    id: 'S-Q34',
    number: 34,
    section: 'Section E — Assessment & Feedback',
    text: 'How timely is the feedback you receive on your work?',
    type: 'single',
    options: scale(['Much too late to be useful', 'Somewhat too late', 'About the right time', 'Usually timely', 'Very timely'], ['I have not received feedback']),
    indicatorId: 'IND-FBT-01',
    constructId: 'feedback-timeliness',
    whyThisRespondent: 'Students experience when feedback arrives relative to when they could still act on it. Recorded turnaround provides the objective counterpart.',
  },
  {
    id: 'S-Q37',
    number: 37,
    section: 'Section G — Overall Evaluation',
    text: 'Overall, how satisfied are you with your experience of this course?',
    type: 'single',
    options: scale(['Very dissatisfied', 'Dissatisfied', 'Neither satisfied nor dissatisfied', 'Satisfied', 'Very satisfied']),
    indicatorId: 'IND-SAT-01',
    constructId: 'student-satisfaction',
    whyThisRespondent: 'Satisfaction is a direct variable of interest. AQIP measures it plainly and examines its relationship with learning evidence rather than treating it as quality.',
  },
  {
    id: 'S-Q39',
    number: 39,
    section: 'Section H — Diagnostic Questions',
    text: 'What is the single biggest thing that currently makes learning in this course more difficult than it should be?',
    note: 'Open response.',
    type: 'open',
    whyThisRespondent: 'Open responses are stored as qualitative evidence. They illustrate findings; they are not scored.',
  },
];
